stages:
  - prepare
  - deploy
  - tag

prepare:
    stage: prepare
    image: ubuntu:22.10
    before_script:
      - apt update && apt install -y curl gnupg
      - curl -Ls --tlsv1.2 --proto "=https" --retry 3 https://cli.doppler.com/install.sh | sh
      - chmod +x generate_liquibase_properties.sh
    script:
      - doppler secrets download --no-file --format env > .env
      - source ./.env
      - export $(cut -d= -f1 .env)
      - ./generate_liquibase_properties.sh
    environment:
      name: $CI_COMMIT_REF_NAME
    artifacts:
      paths:
        - .env
        - liquibase.properties
      expire_in: 5 mins
    only:
      - develop
      - staging
      - master

deploy:
    stage: deploy
    image: liquibase/liquibase:4.11
    script:
      - liquibase status --verbose
      - liquibase update-sql
      - liquibase update
    environment:
      name: $CI_COMMIT_REF_NAME
    needs: [ prepare ]
    dependencies:
      - prepare
    only:
      - develop
      - staging
      - master

tagging:
    stage: tag
    image: liquibase/liquibase:4.11
    script:
      - liquibase tag $CI_COMMIT_SHORT_SHA
    environment:
      name: $CI_COMMIT_REF_NAME
    needs: [ deploy ]
    dependencies:
      - prepare
    only:
      - develop
      - staging
      - master
