stages:
  - prepare
  - deploy

prepare:
    stage: prepare
    image: ubuntu:22.10
    before_script:
      - apt update && apt install -y curl gnupg
      - curl -Ls --tlsv1.2 --proto "=https" --retry 3 https://cli.doppler.com/install.sh | sh
    script:
      - doppler secrets download --no-file --format env > .env
      - source ./.env
      - export $(cut -d= -f1 .env)
      - chmod +x generate_liquibase_properties.sh
      - ./generate_liquibase_properties.sh
    environment:
      name: $CI_COMMIT_REF_NAME
    artifacts:
      paths:
        - .env
        - liquibase.properties
    only:
      - develop
      - staging
      - master

deploy:
    stage: deploy
    image: ubuntu:22.10
    script:
      - cat .env
      - cat liquibase.properties
    environment:
      name: $CI_COMMIT_REF_NAME
    needs: [ prepare ]
    dependencies:
      - prepare
    only:
      - develop
      - staging
      - master
