name: update database
on:
  push:
    branches:
      - develop
      - staging
      - master

jobs:
  prepare:
    runs-on: self-hosted
    container:
      image: ubuntu:22.10
      options: --user root
    environment: ${{ github.ref_name }}
    steps:
      - uses: actions/checkout@v3
      - name: Install doppler
        run: |
          apt-get update && apt-get install -y curl gnupg
          curl -Ls --tlsv1.2 --proto "=https" --retry 3 https://cli.doppler.com/install.sh | sh
      - name: Generate Env File
        env:
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}
        run: doppler secrets download --no-file --format env > .env
      - name: Export Env File Variables
        uses: cardinalby/export-env-action@v1
        with:
          envFile: '.env'
      - name: Generate Liquibase Properties File
        run: |
          chmod +x generate_liquibase_properties.sh
          ./generate_liquibase_properties.sh
      - name: Upload Liquibase Properties File
        uses: actions/upload-artifact@v3
        with:
          name: liquibase-properties-file
          path: liquibase.properties
          retention-days: 1
  update:
    runs-on: self-hosted
    container:
      image: liquibase/liquibase:4.11
      options: --user root
    environment: ${{ github.ref_name }}
    needs: prepare
    steps:
      - uses: actions/checkout@v3
      - name: Get Liquibase Properties Files
        uses: actions/download-artifact@v3
        with:
          name: liquibase-properties-file
      - name: Update Database
        run: |
          ls -a
          cat liquibase.properties

 