name: update database
on:
  push:
    branches:
      - develop
      - staging
      - master

jobs:
  prepare:
    runs-on: self-hosted
    container: ubuntu:22.10
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - apt update && apt install -y curl gnupg

