name: update database
on:
  push:
    branches:
      - develop
      - staging
      - master

jobs:
  prepare:
    runs-on: ubuntu:22.10
    steps:
      - name: Checkout
        uses: actions/checkout@v3


