name: update database
on:
  push:
    branches:
      - develop
      - staging
      - master

jobs:
  prepare:
    runs-on: self-hosted
    container: ubuntu:22.10
    environment: ${{ github.ref_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install doppler
        run: |
          apt-get update
          apt-get install -y curl gnupg
          curl -Ls --tlsv1.2 --proto "=https" --retry 3 https://cli.doppler.com/install.sh | sh
      - name: Generate Env File
        env:
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}
        run: |
          doppler secrets download --no-file --format env > .env
          cat .env
      - name: Add New Variables
        uses: cardinalby/export-env-action@v1
        with:
          envFile: '.env'
      - name: Generate Properties File
        run: |
          chmod +x generate_liquibase_properties.sh
          ./generate_liquibase_properties.sh
          cat liquibase.properties

