name: update database
on: [ push ]
jobs:
  prepare:
    container: ubuntu:22.10
    steps:
      - apt update && apt install -y curl gnupg
      - curl -Ls --tlsv1.2 --proto "=https" --retry 3 https://cli.doppler.com/install.sh | sh
      - chmod +x generate_liquibase_properties.sh
      - doppler secrets download --no-file --format env > .env
      - source ./.env
      - export $(cut -d= -f1 .env)
      - ./generate_liquibase_properties.sh
      - name: Generate Property Files
        uses: actions/upload-artifact@v3
        with:
          name: properties-files
          path: liquibase.properties
          retention-days: 1
  update:
    container: liquibase/liquibase:4.11
    needs: [ prepare ]
    steps:
      - name: Get Property Files
        uses: actions/download-artifact@v3
        with:
          name: properties-files
      - cat liquibase.properties
