name: update database
on:
  push:
    branches:
      - develop
      - staging
      - master

jobs:
  prepare:
    runs-on: ubuntu:22.10
    steps:
      - sudo apt-get update
      - sudo apt-get install -y curl gnupg

